const { test, expect } = require('@playwright/test');
const { login, adminCsrf, createProvider, createClient, clearActivity } = require('./helpers');

test('global activity renders across clients, searches, and pages', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await login(page);
  const csrf = await adminCsrf(page);
  await clearActivity(page, csrf);
  const providerName = 'browser-activity';
  const modelId = `${providerName}/mock-model`;
  const client1Name = 'activity-client-one';
  const client2Name = 'activity-client-two';
  const provider = await createProvider(page, csrf, providerName);
  const modelsRes = await page.request.get(`/api/admin/providers/${provider.id}/models`);
  expect(modelsRes.ok()).toBeTruthy();
  const realModel = (await modelsRes.json()).data.find(m => m.provider_id === provider.id && m.upstream_model_id === 'mock-model');
  expect(realModel).toBeTruthy();
  const client1 = await createClient(page, csrf, client1Name);
  const client2 = await createClient(page, csrf, client2Name);
  const grant = async clientId => {
    const res = await page.request.put(`/api/admin/client-keys/${clientId}/permissions`, { headers: { 'X-CSRF-Token': csrf }, data: { defaults: [], permissions: [{ kind: 'real', model_id: realModel.id, enabled: true }] } });
    expect(res.status()).toBe(204);
  };
  await grant(client1.id);
  await grant(client2.id);
  const infer = async (secret, content) => {
    const res = await page.request.post('/v1/chat/completions', { headers: { Authorization: `Bearer ${secret}` }, data: { model: modelId, messages: [{ role: 'user', content }] } });
    expect(res.status()).toBe(200);
  };
  for (let i = 0; i < 55; i++) await infer(i % 2 === 0 ? client1.secret : client2.secret, `activity-content-${i}`);
  await page.locator('#nav-links').getByRole('link', { name: 'Settings' }).click();
  await expect(page.locator('#view-settings')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Global activity' })).toBeVisible();
  await expect(page.locator('#global-activity-body tr')).toHaveCount(50);
  await expect(page.locator('#global-activity-count')).toHaveText('1–50');
  await expect(page.locator('#global-activity-prev')).toBeDisabled();
  await expect(page.locator('#global-activity-next')).toBeEnabled();
  await page.locator('#global-activity-search').fill(client2Name);
  await expect(page.locator('#global-activity-body tr')).toHaveCount(27);
  await expect(page.locator('#global-activity-empty')).toBeHidden();
  await page.locator('#global-activity-search').fill('zzz-no-match');
  await expect(page.locator('#global-activity-empty')).toBeVisible();
  await page.locator('#global-activity-search').fill('');
  await expect(page.locator('#global-activity-body tr')).toHaveCount(50);
  await page.locator('#global-activity-next').click();
  await expect(page.locator('#global-activity-body tr')).toHaveCount(5);
  await expect(page.locator('#global-activity-count')).toHaveText('51–55');
  await expect(page.locator('#global-activity-prev')).toBeEnabled();
  await expect(page.locator('#global-activity-next')).toBeDisabled();
  await page.locator('#global-activity-prev').click();
  await expect(page.locator('#global-activity-body tr')).toHaveCount(50);
  await expect(page.locator('#global-activity-count')).toHaveText('1–50');
});

test('activity pagination handles empty results and the exact-page boundary', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await login(page);
  const csrf = await adminCsrf(page);
  await clearActivity(page, csrf);
  const providerName = 'browser-boundary';
  const modelId = `${providerName}/mock-model`;
  const provider = await createProvider(page, csrf, providerName);
  const modelsRes = await page.request.get(`/api/admin/providers/${provider.id}/models`);
  expect(modelsRes.ok()).toBeTruthy();
  const realModel = (await modelsRes.json()).data.find(m => m.provider_id === provider.id && m.upstream_model_id === 'mock-model');
  expect(realModel).toBeTruthy();
  const clientA = await createClient(page, csrf, 'boundary-empty-client');
  const clientB = await createClient(page, csrf, 'boundary-full-client');
  await page.getByRole('link', { name: 'Clients' }).click();
  const clientARow = page.locator('#clients-body tr', { hasText: clientA.name });
  await expect(clientARow).toBeVisible();
  await clientARow.getByRole('button', { name: 'Activity' }).click();
  await expect(page.locator('#activity-dialog')).toBeVisible();
  await expect(page.locator('#activity-empty')).toBeVisible();
  await expect(page.locator('#activity-count')).not.toHaveText('1–0');
  await expect(page.locator('#activity-count')).toHaveText('0 results');
  await expect(page.locator('#activity-prev')).toBeDisabled();
  await expect(page.locator('#activity-next')).toBeDisabled();
  await page.getByRole('button', { name: 'Done' }).click();
  await expect(page.locator('#activity-dialog')).toBeHidden();
  await page.locator('#nav-links').getByRole('link', { name: 'Settings' }).click();
  await expect(page.locator('#view-settings')).toBeVisible();
  await page.locator('#global-activity-search').fill('zzz-no-match-boundary');
  await expect(page.locator('#global-activity-empty')).toBeVisible();
  await expect(page.locator('#global-activity-count')).not.toHaveText('1–0');
  await expect(page.locator('#global-activity-count')).toHaveText('0 results');
  await expect(page.locator('#global-activity-next')).toBeDisabled();
  await page.locator('#global-activity-search').fill('');
  const grantRes = await page.request.put(`/api/admin/client-keys/${clientB.id}/permissions`, { headers: { 'X-CSRF-Token': csrf }, data: { defaults: [], permissions: [{ kind: 'real', model_id: realModel.id, enabled: true }] } });
  expect(grantRes.status()).toBe(204);
  for (let i = 0; i < 50; i++) {
    const res = await page.request.post('/v1/chat/completions', { headers: { Authorization: `Bearer ${clientB.secret}` }, data: { model: modelId, messages: [{ role: 'user', content: `boundary-content-${i}` }] } });
    expect(res.status()).toBe(200);
  }
  await page.getByRole('link', { name: 'Clients' }).click();
  const clientBRow = page.locator('#clients-body tr', { hasText: clientB.name });
  await expect(clientBRow).toBeVisible();
  await clientBRow.getByRole('button', { name: 'Activity' }).click();
  await expect(page.locator('#activity-dialog')).toBeVisible();
  await expect(page.locator('#activity-empty')).toBeHidden();
  await expect(page.locator('#activity-body tr')).toHaveCount(50);
  await expect(page.locator('#activity-count')).toHaveText('1–50');
  await expect(page.locator('#activity-next')).toBeDisabled();
  await expect(page.locator('#activity-prev')).toBeDisabled();
  await page.getByRole('button', { name: 'Clear activity' }).click();
  await expect(page.locator('#confirm-dialog')).toBeVisible();
  await expect(page.locator('#confirm-copy')).toContainText('permanently deleted');
  await page.locator('#confirm-action').click();
  await expect(page.locator('#activity-empty')).toBeVisible();
  await expect(page.locator('#activity-count')).toHaveText('0 results');
  await page.getByRole('button', { name: 'Done' }).click();
  await expect(page.locator('#activity-dialog')).toBeHidden();
});
